# Generated by Django 5.1.4 on 2024-12-09 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalsecuritydevice',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical 安全��备', 'verbose_name_plural': 'historical 安全��备'},
        ),
        migrations.AlterModelOptions(
            name='networkdevice',
            options={'permissions': [('export_networkdevice', '导出网络设备信息'), ('import_networkdevice', '导入网络设备信息')], 'verbose_name': '网络设备', 'verbose_name_plural': '网络设备'},
        ),
        migrations.AlterModelOptions(
            name='securitydevice',
            options={'verbose_name': '安全��备', 'verbose_name_plural': '安全��备'},
        ),
        migrations.AlterModelOptions(
            name='server',
            options={'permissions': [('export_server', '导出服务器信息'), ('import_server', '导入服务器信息')], 'verbose_name': '服务器', 'verbose_name_plural': '服务器'},
        ),
    ]
