# Generated by Django 5.1.4 on 2024-12-09 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_alter_historicalsecuritydevice_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalsecuritydevice',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical 安全设备', 'verbose_name_plural': 'historical 安全设备'},
        ),
        migrations.AlterModelOptions(
            name='securitydevice',
            options={'permissions': [('export_securitydevice', '导出安全设备信息'), ('import_securitydevice', '导入安全设备信息')], 'verbose_name': '安全设备', 'verbose_name_plural': '安全设备'},
        ),
        migrations.AlterModelOptions(
            name='storagedevice',
            options={'permissions': [('export_storagedevice', '导出存储设备信息'), ('import_storagedevice', '导入存储设备信息')], 'verbose_name': '存储设备', 'verbose_name_plural': '存储设备'},
        ),
        migrations.AlterField(
            model_name='historicalnetworkdevice',
            name='management_ip',
            field=models.GenericIPAddressField(db_index=True, verbose_name='��理IP'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='management_ip',
            field=models.GenericIPAddressField(unique=True, verbose_name='��理IP'),
        ),
    ]
