# Generated by Django 5.1.4 on 2024-12-09 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_alter_historicalsecuritydevice_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalserver',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical 服务��', 'verbose_name_plural': 'historical 服务��'},
        ),
        migrations.AlterModelOptions(
            name='networkdevice',
            options={'default_permissions': ('view', 'add', 'change', 'delete'), 'permissions': [('export_networkdevice', '导出网络设备信息'), ('import_networkdevice', '导入网络设备信息')], 'verbose_name': '网络设备', 'verbose_name_plural': '网络设备'},
        ),
        migrations.AlterModelOptions(
            name='securitydevice',
            options={'default_permissions': ('view', 'add', 'change', 'delete'), 'permissions': [('export_securitydevice', '导出安全设备信息'), ('import_securitydevice', '导入安全设备信息')], 'verbose_name': '安全设备', 'verbose_name_plural': '安全设备'},
        ),
        migrations.AlterModelOptions(
            name='server',
            options={'default_permissions': ('view', 'add', 'change', 'delete'), 'permissions': [('export_server', '导出服务器信息'), ('import_server', '导入服务器信息')], 'verbose_name': '服务��', 'verbose_name_plural': '服务��'},
        ),
        migrations.AlterModelOptions(
            name='storagedevice',
            options={'default_permissions': ('view', 'add', 'change', 'delete'), 'permissions': [('export_storagedevice', '导出存储设备信息'), ('import_storagedevice', '导入存储设备信息')], 'verbose_name': '存储设备', 'verbose_name_plural': '存储设备'},
        ),
        migrations.AlterField(
            model_name='historicalnetworkdevice',
            name='management_ip',
            field=models.GenericIPAddressField(db_index=True, verbose_name='管理IP'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='management_ip',
            field=models.GenericIPAddressField(unique=True, verbose_name='管理IP'),
        ),
    ]
