# Generated by Django 5.1.4 on 2024-12-09 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_alter_historicalserver_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='server',
            options={'verbose_name': '服务器', 'verbose_name_plural': '服务器'},
        ),
        migrations.AlterField(
            model_name='server',
            name='business_system',
            field=models.CharField(max_length=50, verbose_name='业务系统'),
        ),
        migrations.AlterField(
            model_name='server',
            name='data_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets.datacenter', verbose_name='数据中心'),
        ),
        migrations.AlterField(
            model_name='server',
            name='hostname',
            field=models.CharField(max_length=50, verbose_name='主机名'),
        ),
        migrations.AlterField(
            model_name='server',
            name='manufacturer',
            field=models.CharField(max_length=50, verbose_name='制造商'),
        ),
        migrations.AlterField(
            model_name='server',
            name='model',
            field=models.CharField(max_length=50, verbose_name='型号'),
        ),
        migrations.AlterField(
            model_name='server',
            name='sn',
            field=models.CharField(max_length=50, unique=True, verbose_name='序列号'),
        ),
        migrations.AlterField(
            model_name='server',
            name='status',
            field=models.CharField(choices=[('running', '运行中'), ('stopped', '已停止'), ('maintenance', '维护中'), ('fault', '故障')], default='running', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='server',
            name='warranty_date',
            field=models.DateField(verbose_name='保修日期'),
        ),
        migrations.DeleteModel(
            name='HistoricalServer',
        ),
    ]
