# Generated by Django 5.1.4 on 2024-12-09 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_alter_server_options_alter_server_business_system_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalnetworkdevice',
            name='status',
            field=models.CharField(choices=[('running', '运行中'), ('stopped', '已停止'), ('maintenance', '维护中'), ('fault', '故障')], default='running', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='historicalsecuritydevice',
            name='status',
            field=models.CharField(choices=[('running', '运行中'), ('stopped', '已停止'), ('maintenance', '维护中'), ('fault', '故障')], default='running', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='historicalstoragedevice',
            name='status',
            field=models.CharField(choices=[('running', '运行中'), ('stopped', '已停止'), ('maintenance', '维护中'), ('fault', '故障')], default='running', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='status',
            field=models.CharField(choices=[('running', '运行中'), ('stopped', '已停止'), ('maintenance', '维护中'), ('fault', '故障')], default='running', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='securitydevice',
            name='status',
            field=models.CharField(choices=[('running', '运行中'), ('stopped', '已停止'), ('maintenance', '维护中'), ('fault', '故障')], default='running', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='server',
            name='data_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets.datacenter', verbose_name='所属数据中心'),
        ),
        migrations.AlterField(
            model_name='server',
            name='manufacturer',
            field=models.CharField(max_length=100, verbose_name='制造商'),
        ),
        migrations.AlterField(
            model_name='server',
            name='model',
            field=models.CharField(max_length=100, verbose_name='型号'),
        ),
        migrations.AlterField(
            model_name='server',
            name='sn',
            field=models.CharField(max_length=100, unique=True, verbose_name='序列号'),
        ),
        migrations.AlterField(
            model_name='server',
            name='warranty_date',
            field=models.DateField(verbose_name='保修期限'),
        ),
        migrations.AlterField(
            model_name='storagedevice',
            name='status',
            field=models.CharField(choices=[('running', '运行中'), ('stopped', '已停止'), ('maintenance', '维护中'), ('fault', '故障')], default='running', max_length=20, verbose_name='状态'),
        ),
    ]
