# Generated by Django 5.1.4 on 2024-12-09 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('assets', '0002_alter_historicalsecuritydevice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='data_centers',
            field=models.ManyToManyField(blank=True, related_name='users', to='assets.datacenter', verbose_name='可访问的数据中心'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', '管理员'), ('user', '普通用户')], default='user', max_length=10, verbose_name='用户类型'),
        ),
    ]
